Lab 1
bogdanoff1337/-panasuk-bogdan-IPZ-32 pull request #4
Opened 2023-09-29 19:01 UTC by bogdanoff1337

lab 1

2023-10-02 16:41 UTC, vozniuk-lntu commented
обмеж мерж гілок без ревю (в гайді є по гіту, я писала сама його)

2023-10-02 17:08 UTC, bogdanoff1337 commented
зробив обмеження

2023-10-04 18:59 UTC, vozniuk-lntu requested changes
виправляєш, робиш коміти
і мені покаже що ти правив
пул цей не закривай, працюєш в ньому

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +    <section class="header ">
в тебе вже є семантичний тег `хедер `не потібна тут ця `секція`

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +          <h5>WebStudio</h5>
це винести з `нав` і це не заголовок, а `посилання` на `індекс.хтмл`

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +            <li><a href="#">Портфоліо</a></li>
не вірні назви пунктів меню (візьми з фігми)
Навігацією є тільки три посилання (студія, портфоліо та контакти)
Пошту та тел винеси за `нав`. Це буде окремий список. і застосуй mailto, tel (гугли)

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +             <li>+38 096 111 11 11</li>
це посилання

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +    <section class="about">
розділи на дві окремі секції https://i.imgur.com/qN8EOuH.png

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +        <h2>Ефективні рішення для вашого бізнесу</h2>
це h1

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +          <h2>Увага до деталей</h2>
це h3, і це має бути в лішці
валідуй свій код на спеціальному сайті, він би показав що тут ерори в розмітці

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +
список картинок

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +          <div class="card">
не вірна структура списку
https://i.imgur.com/13J1IGZ.png
у ul можна вкладати тільки li, а вже у li можна пхати все що треба

2023-10-04 18:59 UTC, vozniuk-lntu commented on index.html
> +        м. Київ, пр-т Лесі Українки, 26<br>
ніякі БР
хай буде все в ряд, потім це стилями виправиться

2023-10-05 16:16 UTC, vozniuk-lntu approved these changes
1. тут шось з шляхом https://i.imgur.com/lVcIJav.png
`./src/images/desktop.jpg` отак прописуй
2. це прибери з картинок `style="width: 270px;"`, габарити просто так задаються `width="270"`

апрув є, виправиш коменти в другій лабі
зливай в мейн
перевір чи деплоїться
нову гілку з мейн робиш
наступна лаба
https://docs.google.com/document/d/1THT3lT1JlDAHJNTSdngiToexdVmUeLbE/edit?usp=sharing&ouid=104518963218417128491&rtpof=true&sd=true
і скрін як буде виглядати (працюєш суто з шрифтами та кольорами)
https://i.imgur.com/tniDQxh.png

2023-10-05 16:16 UTC, vozniuk-lntu commented on index.html
>          м. Київ, пр-т Лесі Українки, 26<br>
обгорни в `р` рядок з адресою

2023-10-05 16:46 UTC, merged